services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      NODE_ENV: production
      # Add any production environment variables here
      # DATABASE_URL: your_database_url
      # API_KEY: your_api_key
    ports:
      - "3000:3000"
    restart: unless-stopped
    # Add healthcheck for production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 